name: wifi_speed_test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^1.1.0
  internet_speed_test: ^1.5.0
  syncfusion_flutter_gauges: ^19.2.62
  percent_indicator: ^3.0.1
  fluttertoast: ^8.0.8
  rflutter_alert: ^2.0.4
  device_information: ^0.0.4
  provider: ^6.0.0
  dart_ipify: ^1.1.1
  shared_preferences: ^2.0.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/tab_test.png
    - assets/icons/tab_settings.png
    - assets/icons//tab_history.png
    - assets/icons/tab_pass.png
    - assets/icons/test.png
    - assets/passwords/passes.txt
    - assets/onboarding/feedback.png
    - assets/onboarding/stats.png
    - assets/onboarding/wifirouter.png

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
